version: '3.8'
services:
    express:
      container_name: pwa-express
      image: 'node:latest'
      working_dir: /home/node/app
      command:
        - /bin/sh
        - '-c'
        - 'npm install && npm start'
      ports:
        - '3001:3001'
      volumes:
        - './src:/home/node/app'
    react:
      container_name: pwa-react
      build:
        context: ./react-pwa
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      volumes:
        - './react-pwa:/app'
        - '/app/node_modules'
      environment:
        - CHOKIDAR_USEPOLLING=true
      stdin_open: true
      tty: true